/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import clases.Categoria;
import clases.Pelicula;
import gestion.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Luis
 */
public class FrmNuevaPelicula extends javax.swing.JDialog {

    /**
     * Creates new form FrmNuevaCategoria
     */
    GestionCategoria listaCats;
    GestionPelicula listaPeli;
    private int operacion, index;

    public FrmNuevaPelicula(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        this.setLocationRelativeTo(null);
        initComponents();

    }

    public FrmNuevaPelicula(java.awt.Frame parent, boolean modal, GestionCategoria cats, GestionPelicula pelis, int op) {
        super(parent, modal);
        this.setLocationRelativeTo(null);
        initComponents();
        this.listaCats = cats;
        this.listaPeli = pelis;
        this.operacion = op; // recive un 1 cuando se inserta y un 2 cuando se edita 

    }

    public FrmNuevaPelicula(java.awt.Frame parent, boolean modal, GestionCategoria lista, int op, int posi, GestionPelicula pelis) {
        super(parent, modal);
        this.setLocationRelativeTo(null);
        initComponents();
        this.listaCats = lista;
        this.listaPeli = pelis;
        this.operacion = op; // recive un 1 cuando se inserta y un 2 cuando se edita 
        this.index = posi;
        txtId.setText(String.valueOf(pelis.getVectPelicula()[this.index].getIdPelicula()));
        txtId.setEditable(false);
        txtTitulo.setText(pelis.getVectPelicula()[index].getTitulo());
        txtDuracion.setText(String.valueOf(pelis.getVectPelicula()[index].getDuracion()));

        txtProtagonista.setText(pelis.getVectPelicula()[index].getProtagonista());
        txtAnio.setText(String.valueOf(pelis.getVectPelicula()[index].getAnio()));
        txtPais.setText(pelis.getVectPelicula()[index].getPais());
        dtpFecha.setDate(pelis.getVectPelicula()[posi].getFechaEstreno());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblId = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        lblTitulo = new javax.swing.JLabel();
        txtTitulo = new javax.swing.JTextField();
        lblDuracion = new javax.swing.JLabel();
        txtDuracion = new javax.swing.JTextField();
        lblCategoria = new javax.swing.JLabel();
        cmbCategoria = new javax.swing.JComboBox<>();
        lblProtagonista = new javax.swing.JLabel();
        txtProtagonista = new javax.swing.JTextField();
        lblAnio = new javax.swing.JLabel();
        txtAnio = new javax.swing.JTextField();
        lblPais = new javax.swing.JLabel();
        txtPais = new javax.swing.JTextField();
        dtpFecha = new com.github.lgooddatepicker.components.DatePicker();
        lblFecha = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnGuardar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Nueva Pelicula");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos de la Pelicula", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP));

        lblId.setText("ID Pelicula :");
        lblId.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        txtId.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdActionPerformed(evt);
            }
        });

        lblTitulo.setText("Titulo :");
        lblTitulo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        txtTitulo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtTitulo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTituloKeyPressed(evt);
            }
        });

        lblDuracion.setText("Duración :");
        lblDuracion.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        txtDuracion.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        lblCategoria.setText("Categoria : ");
        lblCategoria.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        lblProtagonista.setText("Protagonista :");
        lblProtagonista.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        lblAnio.setText("Año :");
        lblAnio.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        txtAnio.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        lblPais.setText("Pais :");
        lblPais.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        txtPais.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        lblFecha.setText("Fecha estreno :");
        lblFecha.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblTitulo)
                            .addComponent(lblId))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblProtagonista)
                            .addComponent(lblDuracion)
                            .addComponent(lblAnio)
                            .addComponent(lblFecha))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblCategoria)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmbCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtProtagonista, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(txtAnio, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(lblPais)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtPais, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(dtpFecha, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblId)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitulo)
                    .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDuracion)
                    .addComponent(lblCategoria)
                    .addComponent(cmbCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProtagonista)
                    .addComponent(txtProtagonista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtAnio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAnio)
                    .addComponent(txtPais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPais))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dtpFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFecha))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/delete (2).jpg"))); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/delete (1).jpg"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(btnGuardar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(btnCancelar)
                .addGap(25, 25, 25))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar)
                    .addComponent(btnGuardar))
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();//cierra solo esta ventana
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        Pelicula peliObj = new Pelicula();
        if (this.operacion == 1) {  //Insertar nuevo registro

            if (txtId.getText().equals("") || txtTitulo.getText().equals("")
                    || txtDuracion.getText().equals("") || cmbCategoria.getSelectedItem().toString().equals("Seleccione Categoría")
                    || txtProtagonista.getText().equals("") || txtAnio.getText().equals("")
                    || txtPais.getText().equals("") || dtpFecha.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Hay campos vacíos");
            } else {
                try {
                    peliObj.setIdPelicula(Integer.parseInt(txtId.getText()));
                    peliObj.setTitulo(txtTitulo.getText());
                    peliObj.setDuracion(Integer.parseInt(txtDuracion.getText()));
                    peliObj.setIdCategoria(cmbCategoria.getSelectedIndex() - 1);
                    peliObj.setProtagonista(txtProtagonista.getText());
                    peliObj.setAnio(Integer.parseInt(txtAnio.getText()));
                    peliObj.setPais(txtPais.getText());
                    peliObj.setFechaEstreno(dtpFecha.getDate());

                    if (listaPeli.insertarPelicula(peliObj)) {
                        JOptionPane.showMessageDialog(null, "Película insertada");
                        txtId.setText("");
                        txtTitulo.setText("");
                        txtDuracion.setText("");
                        cmbCategoria.setSelectedIndex(0);
                        txtProtagonista.setText("");
                        txtAnio.setText("");
                        txtPais.setText("");
                        dtpFecha.setText("");
                        txtId.requestFocus();
                    } else {
                        JOptionPane.showMessageDialog(null, "El vector está lleno");
                    }
                } catch (NumberFormatException e) {
                    JOptionPane.showMessageDialog(null, "El id debe ser numérico");
                    txtId.setText("");
                    txtId.requestFocus();
                }
            }
        } else if (operacion == 2) {  //Editar un registro existente
            if (txtTitulo.getText().equals("")
                    || txtDuracion.getText().equals("") || cmbCategoria.getSelectedIndex()==0
                    || txtProtagonista.getText().equals("") || txtAnio.getText().equals("")
                    || txtPais.getText().equals("") || dtpFecha.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Hay campos vacíos");
            } else {
                try {
                    peliObj.setIdPelicula(Integer.parseInt(txtId.getText()));
                    peliObj.setTitulo(txtTitulo.getText());
                    peliObj.setDuracion(Integer.parseInt(txtDuracion.getText()));
                    peliObj.setIdCategoria(cmbCategoria.getSelectedIndex() - 1);
                    peliObj.setProtagonista(txtProtagonista.getText());
                    peliObj.setAnio(Integer.parseInt(txtAnio.getText()));
                    peliObj.setPais(txtPais.getText());
                    peliObj.setFechaEstreno(dtpFecha.getDate());

                    if (listaPeli.editarPelicula(peliObj, index)) {
                        JOptionPane.showMessageDialog(null, "Película editada");
                        this.dispose();
                    } else {
                        JOptionPane.showMessageDialog(null, "Error de edición");
                    }
                } catch (NumberFormatException e) {
                    JOptionPane.showMessageDialog(null, "Se requiere dato numérico");
                    txtId.setText("");
                    txtId.requestFocus();

                }
            }
        }

    }//GEN-LAST:event_btnGuardarActionPerformed
    
    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        cmbCategoria.removeAllItems();
        cmbCategoria.addItem("Seleccione Categoría");
        for (int i = 0; i < listaCats.getTam(); i++) {
            cmbCategoria.addItem(listaCats.getVectCategoria()[i].getNombreCat());
        }
        if (operacion == 2) {
            cmbCategoria.setSelectedIndex(listaPeli.getVectPelicula()[index].getIdCategoria()+1);
        }
    }//GEN-LAST:event_formWindowActivated

    private void txtTituloKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTituloKeyPressed
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
            btnGuardarActionPerformed(null);
        }
    }//GEN-LAST:event_txtTituloKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmNuevaPelicula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmNuevaPelicula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmNuevaPelicula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmNuevaPelicula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FrmNuevaPelicula dialog = new FrmNuevaPelicula(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JComboBox<String> cmbCategoria;
    private com.github.lgooddatepicker.components.DatePicker dtpFecha;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblAnio;
    private javax.swing.JLabel lblCategoria;
    private javax.swing.JLabel lblDuracion;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblPais;
    private javax.swing.JLabel lblProtagonista;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextField txtAnio;
    private javax.swing.JTextField txtDuracion;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtPais;
    private javax.swing.JTextField txtProtagonista;
    private javax.swing.JTextField txtTitulo;
    // End of variables declaration//GEN-END:variables
}
